# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_ITC_TEAM_ID"] = "Y849S4R6L9"
ENV["FASTLANE_APPLE_ID"] = "jukka.p.miettinen@icloud.com"
ENV["FASTLANE_USERNAME"] = "jukka.p.miettinen@icloud.com"
default_platform(:ios)

platform :ios do
  lane :test do
    scan(scheme: "Unscrabble2000")
  end

  lane :screenshots do
    snapshot 
    frame_screenshots(silver: true)
    deliver(
      force: true,
      ignore_language_directory_validation: true
    )
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :beta do
    # ---------------------------
    # Make sure we don't have any unchecked in files hanging out
    # ---------------------------
    ensure_git_status_clean

    # ---------------------------
    # We better be on release branch
    # ---------------------------
    ensure_git_branch(branch: 'master')

    # ---------------------------
    # Increment our version numbers. This needs to be done for all of our targets (app, notification center, watch etc.). Here the build and version number will match.
    # ---------------------------
    version_number = increment_version_number(
      bump_type: "patch" # Automatically increment patch version number
    )

    #---------------------------
    # Increment build number and store new build number
    #---------------------------
    build_number = increment_build_number

    #---------------------------
    # Commit version bump
    #---------------------------
    commit_version_bump(
      message: '[ci skip] Bump version',
      xcodeproj: "Unscrabble2000.xcodeproj",
      include: %w[Unscrabble/Info.plist],
      force: true
    )

    #---------------------------
    # Build
    #---------------------------
    build_app(
      scheme: "Unscrabble2000",
      workspace: "Unscrabble2000.xcworkspace",
      include_bitcode: true
    )

    #---------------------------
    # Tag the submit
    #---------------------------
    git_tag = "Unscrabble_" + version_number + "." + build_number
    add_git_tag(tag: git_tag)

    #---------------------------
    # Push to GitHub
    #---------------------------
    push_to_git_remote(remote: 'origin', local_branch: 'master', remote_branch: 'master', force: false)
    
    #---------------------------
    # Upload to TF
    #---------------------------
    pilot(skip_submission: true, username: "jukka.p.miettinen@icloud.com")

    #---------------------------
    # Clean up our files
    #---------------------------
    clean_build_artifacts


    #---------------------------
    # Resets git repo to a clean state by discarding uncommitted changes
    #---------------------------
    # reset_git_repo

    # slack(message: "Successfully distributed a new beta build")
  end
end
