# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

ENV["FASTLANE_ITC_TEAM_ID"] = "Y849S4R6L9"
ENV["FASTLANE_APPLE_ID"] = "jukka.p.miettinen@icloud.com"
ENV["FASTLANE_USERNAME"] = "jukka.p.miettinen@icloud.com"
default_platform(:ios)

platform :ios do
  lane :test do
    scan(scheme: "Unscrabble2000")
  end

  lane :screenshots do
    snapshot 
    frameit(white: true)
    deliver(
      force: true,
      ignore_language_directory_validation: true,
      skip_binary_upload: true
    )
  end

  desc "Description of what the lane does"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(xcodeproj: "Unscrabble2000.xcodeproj")

    # Commit the version bump
    commit_version_bump(xcodeproj: "Unscrabble2000.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # sync_code_signing(type: "appstore")

    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "Unscrabble2000",
            workspace: "Unscrabble2000.xcworkspace",
            include_bitcode: true)
    upload_to_testflight
    # slack(message: "Successfully distributed a new beta build")
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  lane :testflight do
    # ---------------------------
    # Make sure we don't have any unchecked in files hanging out
    # ---------------------------
    ensure_git_status_clean

    # ---------------------------
    # We better be on release branch
    # ---------------------------
    ensure_git_branch(branch: 'master')

    # ---------------------------
    # Increment our version numbers. This needs to be done for all of our targets (app, notification center, watch etc.). Here the build and version number will match.
    # ---------------------------
    increment_build_number(xcodeproj: "Unscrabble2000.xcodeproj")

    #---------------------------
    # Commit version bump
    #---------------------------
    commit_version_bump(xcodeproj: "Unscrabble2000.xcodeproj")

    #---------------------------
    # Build
    #---------------------------
    build_app(scheme: "Unscrabble2000",
            workspace: "Unscrabble2000.xcworkspace",
            include_bitcode: true)

    #---------------------------
    # Upload to TF
    #---------------------------
    pilot(skip_submission: true, username: "jukka.p.miettinen@icloud.com")

    #---------------------------
    # Tag the submit
    #---------------------------
    add_git_tag tag: version_number

    #---------------------------
    # Push to GitHub
    #---------------------------
    push_to_git_remote(remote: 'origin', local_branch: 'master', remote_branch: 'master', force: true)

    #---------------------------
    # Clean up our files
    #---------------------------
    clean_build_artifacts

    # slack(message: "Successfully distributed a new beta build")
  end
end
