# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["FASTLANE_ITC_TEAM_ID"] = "Y849S4R6L9"
ENV["FASTLANE_APPLE_ID"] = "jukka.p.miettinen@icloud.com"
ENV["FASTLANE_USERNAME"] = "jukka.p.miettinen@icloud.com"
default_platform(:ios)

platform :ios do
  lane :test do
    scan(scheme: "Unscrabble2000")
  end

  lane :screenshots do
    snapshot 
    frameit(white: true)
    deliver
  end

  desc "Description of what the lane does"
  lane :beta do
    # Ensure that your git status is not dirty
    ensure_git_status_clean

    # Increment the build number (not the version number)
    # Providing the xcodeproj is optional
    increment_build_number(xcodeproj: "Unscrabble2000.xcodeproj")

    # Commit the version bump
    commit_version_bump(xcodeproj: "Unscrabble2000.xcodeproj")

    # Add a git tag for this build. This will automatically
    # use an appropriate git tag name
    add_git_tag

    # Push the new commit and tag back to your git remote
    push_to_git_remote

    # sync_code_signing(type: "appstore")

    get_certificates           # invokes cert
    get_provisioning_profile   # invokes sigh
    build_app(scheme: "Unscrabble2000",
            workspace: "Unscrabble2000.xcworkspace",
            include_bitcode: true)
    upload_to_testflight
    # slack(message: "Successfully distributed a new beta build")
  end
end
